<?php

use Krystal\Form\Element;

$asClient = !is_array($invoice);

?>

<div class="row">
    <div class="col-lg-6">
        <h2 class="page-header">
            <?php $this->show($title); ?>

            <?php if ($asClient): ?>
            <small class="text-muted">(<?= $invoice['product']; ?>)</small>
            <?php endif; ?>
        </h2>

        <?php $this->loadPartial('breadcrumbs'); ?>
        <?php $this->loadPartial('flash'); ?>
        <form class="form-horizontal">
          <?= Element::hidden('id', $invoice['id']); ?>
          <fieldset>
            <div class="form-group">
              <label for="inputName" class="col-lg-2 control-label"><?php $this->show('Your name'); ?></label>
              <div class="col-lg-10">
                <?= Element::text('client', $invoice['client'], ['class' => 'form-control', 'id' => 'inputName', 'placeholder' => $this->translate('Type your name')]); ?>
              </div>
            </div>

            <div class="form-group">
              <label for="inputEmail" class="col-lg-2 control-label"><?php $this->show('Email'); ?></label>
              <div class="col-lg-10">
                <?= Element::text('email', $invoice['email'], ['class' => 'form-control', 'id' => 'inputEmail', 'placeholder' => $this->translate('Type your email')]); ?>
              </div>
            </div>

            <div class="form-group">
              <label for="inputPhone" class="col-lg-2 control-label"><?php $this->show('Phone'); ?></label>
              <div class="col-lg-10">
                <?= Element::text('phone', $invoice['phone'], ['class' => 'form-control', 'id' => 'inputPhone', 'placeholder' => $this->translate('Type your phone')]); ?>
              </div>
            </div>
            
            <?php if (!$asClient): ?>
            <div class="form-group">
              <label for="inputProduct" class="col-lg-2 control-label"><?php $this->show('Product'); ?></label>
              <div class="col-lg-10">
                <?= Element::text('product', $invoice['product'], ['class' => 'form-control', 'id' => 'inputProduct', 'placeholder' => $this->translate('Product name')]); ?>
              </div>
            </div>
            <?php else: ?>
            <?= Element::hidden('product', $invoice['product']); ?>
            <?php endif; ?>

            <?php if (!$asClient): ?>
            <div class="form-group">
              <label for="inputAmount" class="col-lg-2 control-label"><?php $this->show('Amount'); ?></label>
              <div class="col-lg-10">
                <?= Element::number('amount', $invoice['amount'], ['class' => 'form-control', 'min' => 1, 'id' => 'inputAmount', 'placeholder' => $this->translate('Amount to be charged')]); ?>
              </div>
            </div>

            <?php else: ?>
            <?= Element::hidden('amount', $invoice['amount']); ?>
            <?php endif; ?>

            <?php if ($asClient): ?>
            <div class="form-group">
                <label for="inputCaptcha" class="col-lg-2 control-label"></label>
                <div class="col-lg-10">
                    <a href="#" title="<?php $this->show('Click to refresh'); ?>" data-captcha="button-refresh"><img data-captcha="image" src="<?php echo $this->url('Site:Site@captchaAction', null); ?>" /></a>
                </div>
            </div>
            
            <div class="form-group">
                <label for="inputCaptcha" class="col-lg-2 control-label"></label>
                <div class="col-lg-10">
                    <input type="text" class="form-control" id="inputCaptcha" name="captcha" placeholder="<?php $this->show("Prove that you are not a bot"); ?>" />
                </div>
            </div>
            <?php endif; ?>
            
            <div class="form-group">
              <div class="col-lg-10 pull-right">
                <button type="submit" class="btn btn-success"><?php $this->show('Submit'); ?></button>
              </div>
            </div>
          </fieldset>
        </form>
    </div>

    <div class="col-lg-6">
        <img class="img-responsive" src="<?= $this->asset('img/invoice.png'); ?>" />
    </div>
</div>

