<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Site\Collection\StatusCollection;

?>

<h2 class="page-header"><?php $this->show('Invoices'); ?></h2>

<?php $this->loadPartial('flash'); ?>

<?= Grid::render($invoices, [
    // A column to be considered as a primary key
    'pk' => 'id',
    'batch' => false,
    'columns' => [
        [
            'column' => 'id',
            'label' => 'ID'
        ],

        [
            'column' => 'product'
        ],

        [
            'column' => 'client'
        ],

        [
            'column' => 'email'
        ],

        [
            'column' => 'phone'
        ],

        [
            'column' => 'status',
            'translateable' => true,
            'value' => function($row){
                return (new StatusCollection)->findByKey($row['status']);
            }
        ],

        [
            'column' => 'datetime'
        ],

        [
            'column' => 'amount',
            'value' => function($row){
                return number_format($row['amount']);
            }
        ]
    ],
    
    'actions' => [
        'notify' => function($row){
            if ($row['status'] == 1) {
                return null;
            }

            return Element::icon('glyphicon glyphicon-envelope', $this->url('Site:Admin:Invoice@notifyAction', $row['token']), ['title' => $this->translate('Notify client about payment')]);
        },

        'edit' => function($row){
            if ($row['status'] == 1) {
                return null;
            }

            return Element::icon('glyphicon glyphicon-pencil', $this->url('Site:Admin:Invoice@editAction', $row['token']), ['title' => $this->translate('Edit this invoice')]);
        },

        'delete' => function($row){
            if ($row['status'] == 1) {
                return null;
            }

            return Element::icon('glyphicon glyphicon-trash', $this->url('Site:Admin:Invoice@deleteAction', $row['id']), ['title' => $this->translate('Delete this invoice')]);
        }
    ]

], $this->translator); ?>

<?php $this->loadPartial('paginator'); ?>
