<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;

?>

<h2 class="page-header"><?php $this->show('Invoices'); ?></h2>

<?= Grid::render($invoices, [
    // A column to be considered as a primary key
    'pk' => 'id',
    'batch' => false,
    'columns' => [
        [
            'column' => 'id',
            'label' => 'ID'
        ],

        [
            'column' => 'product'
        ],

        [
            'column' => 'client'
        ],

        [
            'column' => 'email'
        ],

        [
            'column' => 'phone'
        ],

        [
            'column' => 'status'
        ],
        
        [
            'column' => 'datetime'
        ],

        [
            'column' => 'amount',
            'value' => function($row){
                return number_format($row['amount']);
            }
        ]
    ],
    
    'actions' => [
        'notify' => function($row){
            return Element::icon('glyphicon glyphicon-envelope', $this->url('Site:Invoice@notifyAction', $row['token']), ['title' => 'Notify client about payment']);
        },

        'edit' => function($row){
            return Element::icon('glyphicon glyphicon-pencil', $this->url('Site:Invoice@editAction', $row['token']), ['title' => 'Edit this invoice']);
        },

        'delete' => function($row){
            return Element::icon('glyphicon glyphicon-trash', $this->url('Site:Invoice@deleteAction', $row['id']), ['title' => 'Delete this invoice']);
        }
    ]

]); ?>