<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;
use Site\Collection\StatusCollection;

?>

<h2 class="page-header"><i class="glyphicon glyphicon-list-alt"></i> <?php $this->show('Invoices'); ?></h2>

<p>
    <a class="btn btn-primary" href="<?= $this->url('Site:Admin:Invoice@addAction'); ?>"><i class="glyphicon glyphicon-pencil"></i> <?php $this->show('Create invoice'); ?></a>
</p>

<?php $this->loadPartial('flash'); ?>

<?= Grid::render($invoices, [
    // A column to be considered as a primary key
    'pk' => 'id',
    'batch' => false,
    'rowAttributes' => [
        'class' => function($row){
            return $row['status'] == StatusCollection::PARAM_STATUS_COMPLETE ? 'success' : 'warning';
        }
    ],
    'columns' => [
        [
            'column' => 'id',
            'label' => 'ID'
        ],

        [
            'column' => 'product'
        ],

        [
            'column' => 'client'
        ],

        [
            'column' => 'email'
        ],

        [
            'column' => 'phone'
        ],

        [
            'column' => 'status',
            'translateable' => true,
            'value' => function($row){
                return (new StatusCollection)->findByKey($row['status']);
            }
        ],

        [
            'column' => 'datetime'
        ],

        [
            'column' => 'amount',
            'value' => function($row) use ($currency){
                // If has false-like value
                if (!$row['amount']) {
                    return '-';
                }

                // Otherwise return formatted value with currency
                return number_format($row['amount'])  . PHP_EOL . $currency;
            }
        ]
    ],

    'actions' => [
        'notify' => function($row){
            if ($row['status'] == 1 || !$row['amount']) {
                return null;
            }

            return Element::icon('glyphicon glyphicon-envelope', $this->url('Site:Admin:Invoice@notifyAction', $row['token']), ['title' => $this->translate('Notify client about payment')]);
        },

        'edit' => function($row){
            if ($row['status'] == 1) {
                return null;
            }

            return Element::icon('glyphicon glyphicon-pencil', $this->url('Site:Admin:Invoice@editAction', $row['token']), ['title' => $this->translate('Edit this invoice')]);
        },

        'delete' => function($row){
            if ($row['status'] == 1) {
                return null;
            }

            return Element::icon('glyphicon glyphicon-trash', $this->url('Site:Admin:Invoice@deleteAction', $row['id']), ['title' => $this->translate('Delete this invoice')]);
        }
    ]

], $this->translator); ?>

<?php $this->loadPartial('paginator'); ?>
