
<h2 class="page-header"><?php $this->show('Enter account'); ?></h2>

<form class="form-horizontal">
  <fieldset class="col-lg-5">
    <div class="form-group">
      <label for="inputLogin" class="col-lg-2 control-label"><?php $this->show('Login'); ?></label>
      <div class="col-lg-10">
        <input type="text" class="form-control" name="login" id="inputLogin" placeholder="<?php $this->show('Type your login'); ?>" />
      </div>
    </div>

    <div class="form-group">
      <label for="inputPassword" class="col-lg-2 control-label"><?php $this->show('Password'); ?></label>
      <div class="col-lg-10">
        <input type="password" class="form-control" name="password" id="inputPassword" placeholder="<?php $this->show('Type your password'); ?>" />
        <div class="checkbox">
          <label>
            <input type="hidden" name="remember" value="0" />
            <input type="checkbox" name="remember" value="1" /> <?php $this->show('Remember me'); ?>
          </label>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <button type="submit" class="btn btn-primary"><?php $this->show('Login'); ?></button>
      </div>
    </div>
  </fieldset>
</form>